import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
const {height, width} = Dimensions.get('screen');

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  backCover:{
    width:50,
    height:50,
    borderRadius:100,
    backgroundColor:'#fff',
    position:'absolute',
    top:hp('4%'),
    justifyContent:'center',
    alignItems:'center',
    left:20,
    zIndex:900
  },
  mapStyle: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  changeStyle: {
    width: wp('100%'),
    height: 360,
    flexDirection: 'row',
    backgroundColor: '#fff',
    position: 'absolute',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    bottom: hp('0%'),
    zIndex: 9000,
    paddingRight: 30,
    // elevation: 4,
    // shadowRadius: 5,
    // overflow:'hidden'
  },
  changeStyleInner: {
    height: 60,
    width: wp('80%'),
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  smLocImg: {
    width: 35,
    height: 35,
    resizeMode: 'center',
  },
  changeText: {
    fontSize: 16,
    color: '#000',
    fontFamily: 'AnekLatin-Regular',
    lineHeight: 20,
    letterSpacing: 0.2,
    textTransform: 'capitalize',
    marginLeft: 40,
  },

  circleCover: {
    position: 'absolute',
    width: 200,
    right: -110,
    top: hp('40%'),
  },
  circleOne1: {
    width: 60,
    height: 60,
    borderRadius: 100,
    backgroundColor: '#f5f5f5',
    // elevation:4,
    shadowRadius: 5,
    marginBottom: 15,
    marginRight: 20,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9000,
  },
  circleOne: {
    width: 60,
    height: 60,
    borderRadius: 100,
    backgroundColor: '#000',
    elevation: 4,
    shadowRadius: 5,
    marginTop: 10,
    marginBottom: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logImg: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    alignSelf: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  logImg1: {
    width: 80,
    height: 80,
    // resizeMode:'contain',
    alignSelf: 'center',
    marginLeft: 0,
    borderRadius: 100,
  },

  subName: {
    fontSize: 12,
    color: '#757575',
    marginTop: 5,
  },

  sortCover: {
    borderWidth: 0,
    borderColor: '#f3f4f5',
    borderStyle: 'solid',
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#bfbfbf',
    marginRight: 5,
    paddingHorizontal:10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  sortCoverSelected: {
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: 30,
    borderWidth: 0,
    borderColor: '#fff',
    borderStyle: 'solid',
    marginRight: 5,
    elevation: 1,
    backgroundColor: '#9ACD32',
  },
  sortCover1: {
    borderWidth: 0,
    borderColor: '#f3f4f5',
    borderStyle: 'solid',
    borderRadius: 6,
    height: 180,
    width: 180,
    marginRight: 10,
    alignItems: 'center',
    paddingTop: 10,
    backgroundColor: '#f5f5f5',
  },
  sortCoverSelected1: {
    borderWidth: 0,
    borderColor: '#f3f4f5',
    borderStyle: 'solid',
    borderRadius: 6,
    height: 180,
    width: 180,
    marginRight: 10,
    backgroundColor: '#000',
  },
  sortName: {
    padding: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: '#454545',
    fontFamily: 'AnekLatin-Regular',
  },
  sortNameSelected: {
    padding: 10,
    paddingVertical: 10,
    fontSize: 14,
    color: '#fff',
    fontFamily: 'AnekLatin-Regular',
  },
  topCover: {
    width: wp('98%'),
    position: 'absolute',
    top: hp('-0.5%'),
    paddingTop: 0,
    zIndex: 3,
    alignSelf: 'center',
    alignItems: 'center',
    paddingTop: 20,
  },
  layerTwo: {
    width: wp('98%'),
    marginBottom: 10,
    paddingHorizontal: 20,
   
  },
  brandImg: {
    width: 40,
    height: 40,
    paddingVertical: 8,
    marginLeft: 5,
    resizeMode:'contain'
  },
  brandImgSm: {
    width: 20,
    height: 20,
    paddingVertical: 5,
    marginTop:9,
    marginLeft: 8,
    resizeMode:'contain'
  },
  selectCover:{
width:'100%',
paddingHorizontal:20,
alignItems:'flex-start',
paddingBottom:10,
  },
  selectText:{
    fontSize: 12,
    color: '#757575',
    fontFamily: 'AnekLatin-Medium',
    lineHeight: 20,
    letterSpacing: 0.2,
    textTransform: 'capitalize',
  },
  getLocCover:{
    width:wp('88%'),
    flexDirection:'row',
    justifyContent:'flex-start',
    padding:10,
    paddingLeft:18,
    borderWidth:1,
    backgroundColor:'#FFF',
    borderColor:"#f5f5f5",
    borderStyle:'solid',
    alignSelf:'center',
    marginBottom:10,
    borderRadius:30,
    elevation:2,
    shadowRadius: 3,
  },
  touchText:{
    fontSize: 14,
    color: '#212121',
    fontFamily: Platform.OS === 'ios' ? "Arial Hebrew" : "AnekLatin-Regular",
    lineHeight: 20,
    letterSpacing: 0.2,
    paddingVertical:5, 
    marginLeft:15,
  },
  smLogImg:{
    width:30,
    height:30,
    resizeMode:'contain',
   
  },
  welcomeCover:{
    width:wp('100%'),
    padding:20,
  },
  smText:{
    fontSize: 14,
    color: '#212121',
    fontFamily: Platform.OS === 'ios' ? "Arial Hebrew" : "AnekLatin-Regular",
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  bgText:{
    fontSize: 24,
    color: '#212121',
    fontFamily: "AnekLatin-SemiBold",
    lineHeight: 28,
    letterSpacing: 0.2,
  },
  displayModal:{
    width:wp('90%'),
    padding:20,
    paddingVertical:10,
    backgroundColor:'#fff',
    borderRadius:10,
    position:'absolute',
    top:hp('42%'),
    alignSelf:'center',
    flexDirection:'row',
    justifyContent:'flex-start',
    elevation:8
  },
  displayText:{
    fontSize: 18,
    color: '#212121',
    fontFamily: "AnekLatin-SemiBold",
    lineHeight: 22,
    letterSpacing: 0.2,
    marginTop:8,
    marginLeft:5
  },
  mdLogImg:{
    marginTop:5
  }
});

export default styles;
